### PR TITLE
changed tab bar style

### PR DESCRIPTION
**Pull request by 666tos**
adding scrolling functionality to TabBar according to https://github.com/CosmicMind/Material/issues/642

### CODE REVIEW

**Comment by daniel-jonathan** [comment]
This PR changes a project, which is using a version that is not releasable yet. So the PR wont have an affect as I am changing the sample. For that reason I am closing it, otherwise, I appreciate the PR :) Thank you!

**Comment by daniel-jonathan** [comment]
Sorry, I didn't see the other PR in Material's development. Reopening this :) Thank you!

**Comment by 666tos** [comment]
This is pull request in Material which is demonstrated in this sample - https://github.com/CosmicMind/Material/pull/762

**Comment by daniel-jonathan** [comment]
@666tos Just merged it into a temp branch to test it out :) doing the same with this one. Thank you! I am excited to see this in action.

**Comment by daniel-jonathan** [comment]
So the merge conflicts in this will be annoying to deal with, so I am copying the few lines to test the sample. Thank you.

**Comment by 666tos** [comment]
ok, thanks!

**Comment by daniel-jonathan** [comment]
Works like a charm, thank you!

**Comment by Kalpeshsurve21** [comment]
@danieldahan can you please release the new version with scrolling tabbar functionality? So that we can be able to add as many tabs as we want.

**Comment by daniel-jonathan** [comment]
@Kalpeshsurve21 Yeah, working on it. The next release will have many new things, including a scrollable TabBar. My aim will be to have it out within a week max.

**Pull request closed without merging**
